import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeContextProvider from '../contexts/ThemeContext'
import { BookProvider } from './BookProvider'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Book Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <BookProvider>{children}</BookProvider>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
